// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	Password     string
	RefreshToken sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
