// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type HealthCheck struct {
	ID             uuid.UUID
	MonitorID      uuid.UUID
	StatusCode     sql.NullInt32
	ResponseTimeMs int32
	IsSuccess      bool
	ErrorMessage   sql.NullString
	CheckedAt      time.Time
	CreatedAt      time.Time
}

type Monitor struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Name               string
	Url                string
	Method             string
	Headers            pqtype.NullRawMessage
	Body               sql.NullString
	Interval           int32
	ExpectedStatusCode sql.NullInt32
	Timeout            int32
	Status             string
	DeletedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	Revoked   sql.NullBool
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
