// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countMonitorsByUserID = `-- name: CountMonitorsByUserID :one
SELECT COUNT(*) FROM monitors WHERE user_id = $1 AND status = COALESCE(NULLIF($2, ''), status)
`

type CountMonitorsByUserIDParams struct {
	UserID uuid.UUID
	Status interface{}
}

func (q *Queries) CountMonitorsByUserID(ctx context.Context, arg CountMonitorsByUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitorsByUserID, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHealthCheck = `-- name: CreateHealthCheck :exec
INSERT INTO health_checks (
    id,
    monitor_id,
    status_code,
    response_time_ms,
    is_success,
    error_message,
    checked_at,
    created_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateHealthCheckParams struct {
	ID             interface{}
	MonitorID      uuid.UUID
	StatusCode     sql.NullInt32
	ResponseTimeMs sql.NullInt32
	IsSuccess      bool
	ErrorMessage   sql.NullString
	CheckedAt      time.Time
	CreatedAt      time.Time
}

// -------------- Health Check Queries
func (q *Queries) CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) error {
	_, err := q.db.ExecContext(ctx, createHealthCheck,
		arg.ID,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.IsSuccess,
		arg.ErrorMessage,
		arg.CheckedAt,
		arg.CreatedAt,
	)
	return err
}

const createMonitor = `-- name: CreateMonitor :exec

INSERT INTO monitors (
    id, 
    user_id, 
    name, 
    url, 
    method, 
    headers, 
    body, 
    interval, 
    expected_status_code,
    timeout,
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
`

type CreateMonitorParams struct {
	ID                 interface{}
	UserID             uuid.UUID
	Name               string
	Url                string
	Method             string
	Headers            pqtype.NullRawMessage
	Body               sql.NullString
	Interval           int32
	ExpectedStatusCode sql.NullInt32
	Timeout            int32
}

// Monitor Queries
func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) error {
	_, err := q.db.ExecContext(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.Body,
		arg.Interval,
		arg.ExpectedStatusCode,
		arg.Timeout,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec

INSERT INTO refresh_tokens (
    id, 
    user_id, 
    token_hash,
    expires_at, 
    revoked, 
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
`

type CreateRefreshTokenParams struct {
	ID        interface{}
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// Refresh Token Queries
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, 
    name, 
    email, 
    password, 
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    NOW(),
    NOW()
 )
`

type CreateUserParams struct {
	ID       interface{}
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	return err
}

const deleteAllExpired = `-- name: DeleteAllExpired :exec
DELETE FROM refresh_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteAllExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllExpired)
	return err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, name, email, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT id, name, email, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByTokenHash = `-- name: FindByTokenHash :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at, updated_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) FindByTokenHash(ctx context.Context, tokenhash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findByTokenHash, tokenhash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMonitorsByUserID = `-- name: FindMonitorsByUserID :many
SELECT id, user_id, name, url, method, headers, body, interval, expected_status_code, timeout, status, deleted_at, created_at, updated_at FROM monitors
WHERE user_id = $1
AND status = COALESCE(NULLIF($2, ''), status)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type FindMonitorsByUserIDParams struct {
	UserID     uuid.UUID
	Status     interface{}
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) FindMonitorsByUserID(ctx context.Context, arg FindMonitorsByUserIDParams) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, findMonitorsByUserID,
		arg.UserID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Body,
			&i.Interval,
			&i.ExpectedStatusCode,
			&i.Timeout,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMonitors = `-- name: GetAllMonitors :many
SELECT id, user_id, name, url, method, headers, body, interval, expected_status_code, timeout, status, deleted_at, created_at, updated_at FROM monitors 
WHERE status = 'ACTIVE'
ORDER BY created_at ASC
`

func (q *Queries) GetAllMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, getAllMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Body,
			&i.Interval,
			&i.ExpectedStatusCode,
			&i.Timeout,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllByUser = `-- name: RevokeAllByUser :exec
UPDATE refresh_tokens SET 
    revoked = true,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

func (q *Queries) RevokeAllByUser(ctx context.Context, userid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllByUser, userid)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens SET 
    revoked = true,
    updated_at = CURRENT_TIMESTAMP
WHERE token_hash = $1
RETURNING 1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int32, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, tokenHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const update = `-- name: Update :exec
UPDATE users SET
    name = $1,
    email = $2,
    password = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateParams struct {
	Name     string
	Email    string
	Password string
	ID       uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	return err
}
