// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec

INSERT INTO refresh_tokens (
    id, 
    user_id, 
    token_hash,
    expires_at, 
    revoked, 
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
`

type CreateRefreshTokenParams struct {
	ID        interface{}
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// Refresh Token Queries
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, 
    name, 
    email, 
    password, 
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    NOW(),
    NOW()
 )
`

type CreateUserParams struct {
	ID       interface{}
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	return err
}

const deleteAllExpired = `-- name: DeleteAllExpired :exec
DELETE FROM refresh_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteAllExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllExpired)
	return err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, name, email, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT id, name, email, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByTokenHash = `-- name: FindByTokenHash :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at, updated_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) FindByTokenHash(ctx context.Context, tokenhash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findByTokenHash, tokenhash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllByUser = `-- name: RevokeAllByUser :exec
UPDATE refresh_tokens SET 
    revoked = true,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

func (q *Queries) RevokeAllByUser(ctx context.Context, userid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllByUser, userid)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens SET 
    revoked = true,
    updated_at = CURRENT_TIMESTAMP
WHERE token_hash = $1
RETURNING 1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int32, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, tokenHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const update = `-- name: Update :exec
UPDATE users SET
    name = $1,
    email = $2,
    password = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateParams struct {
	Name     string
	Email    string
	Password string
	ID       uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	return err
}
