// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, 
    name, 
    email, 
    password, 
    refresh_token, 
    created_at, 
    updated_at
) VALUES (
    COALESCE($1, gen_random_uuid()),
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
 )
`

type CreateUserParams struct {
	ID           interface{}
	Name         string
	Email        string
	Password     string
	RefreshToken sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.RefreshToken,
	)
	return err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, name, email, password, refresh_token, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT id, name, email, password, refresh_token, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :exec
UPDATE users SET
    name = $1,
    email = $2,
    password = $3,
    refresh_token = $4,
    updated_at = NOW()
WHERE id = $5
`

type UpdateParams struct {
	Name         string
	Email        string
	Password     string
	RefreshToken sql.NullString
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.RefreshToken,
		arg.ID,
	)
	return err
}
